import assert from 'node:assert/strict'
import { test } from 'node:test'
import type { TestContext } from 'node:test'
import { randomUUID } from 'node:crypto'
import { fixture, config, DAY } from './request-fixture.ts'

async function lifecycle(t:TestContext) {
  const f=await fixture(t), path='/organizations/'+f.orgId
  const call=(user=f.owner,suffix='',body?:Record<string,unknown>,selectedApi=f.api,headers:Record<string,string>={})=>selectedApi.handle(new Request(config.apiOrigin+path+suffix,{method:body?'POST':'GET',headers:{origin:config.webOrigin,cookie:'envhandoff-dev-session='+user.token,'x-csrf-token':user.csrf,...(body?{'content-type':'application/json'}:{}),...headers},body:body?JSON.stringify(body):undefined}))
  const recent=(user=f.owner,at=f.now())=>f.db.run('INSERT INTO reauthentications VALUES($1,$2) ON CONFLICT(session_hash) DO UPDATE SET verified_at=excluded.verified_at',user.hash,at)
  return {...f,call,recent}
}

test('Owner changes require current Owner and recent current-session factor verification without changing file grants',async t=>{
  const f=await lifecycle(t), suffix='/members/'+f.receiver.id+'/role', body={role:'owner'}
  assert.equal((await f.call(f.owner,suffix,body)).status,403)
  await f.recent(f.receiver)
  assert.equal((await f.call(f.owner,suffix,body)).status,403)
  assert.equal((await f.call(f.receiver,suffix,body)).status,403)
  await f.recent(f.owner,f.now()+1);assert.equal((await f.call(f.owner,suffix,body)).status,403)
  await f.recent(f.owner,f.now()-15*60_000);assert.equal((await f.call(f.owner,suffix,body)).status,403)
  await f.recent(f.owner,f.now()-15*60_000+1)
  assert.equal((await f.call(f.owner,suffix,body,f.api,{'x-csrf-token':'wrong'})).status,403)
  assert.equal((await f.call(f.owner,suffix,{...body,receive:true})).status,400)
  assert.equal((await f.call(f.owner,suffix,{role:'admin'})).status,400)
  assert.equal((await f.call(f.owner,'/members/'+randomUUID()+'/role',body)).status,404)
  const grants=await f.db.all('SELECT * FROM environment_permissions ORDER BY user_id'),teams=await f.db.all('SELECT * FROM team_members ORDER BY user_id')
  assert.equal((await f.call(f.owner,suffix,body)).status,200)
  assert.equal((await f.call(f.owner,suffix,body)).status,200)
  assert.deepEqual(await f.db.all('SELECT * FROM environment_permissions ORDER BY user_id'),grants)
  assert.deepEqual(await f.db.all('SELECT * FROM team_members ORDER BY user_id'),teams)
  await f.db.run('UPDATE users SET disabled=1 WHERE id=$1',f.other.id)
  assert.equal((await f.call(f.owner,'/members/'+f.other.id+'/role',body)).status,404)
  await f.db.run('UPDATE organizations SET active=0 WHERE id=$1',f.orgId)
  assert.equal((await f.call(f.owner,suffix,{role:'member'})).status,403)
})

test('Owner transfer is atomic, cancels former Owner invitations and racing demotions keep an active Owner',async t=>{
  const f=await lifecycle(t);await f.recent();await f.recent(f.receiver)
  const pending=await f.organizations.issueMember(f.owner.id,f.orgId,f.teamId,{id:'99',login:'future-member'})
  assert.equal((await f.call(f.owner,'/owner-transfer',{userId:f.owner.id})).status,400)
  assert.equal((await f.call(f.owner,'/owner-transfer',{userId:randomUUID()})).status,404)
  const permissions=await f.db.all('SELECT * FROM environment_permissions ORDER BY user_id')
  assert.equal((await f.call(f.owner,'/owner-transfer',{userId:f.receiver.id})).status,200)
  assert.equal((await f.db.get('SELECT role FROM memberships WHERE org_id=$1 AND user_id=$2',f.orgId,f.owner.id))!.role,'member')
  assert.equal((await f.db.get('SELECT role FROM memberships WHERE org_id=$1 AND user_id=$2',f.orgId,f.receiver.id))!.role,'owner')
  assert.equal((await f.db.get('SELECT status FROM invitations WHERE id=$1',pending.id))!.status,'cancelled')
  assert.deepEqual(await f.db.all('SELECT * FROM environment_permissions ORDER BY user_id'),permissions)
  assert.equal((await f.call(f.owner,'/members/'+f.sender.id+'/role',{role:'owner'})).status,403)
  assert.equal((await f.call(f.receiver,'/members/'+f.receiver.id+'/role',{role:'member'})).status,409)
  assert.equal((await f.call(f.receiver,'/members/'+f.owner.id+'/role',{role:'owner'})).status,200)
  const results=await Promise.all([f.call(f.owner,'/members/'+f.owner.id+'/role',{role:'member'}),f.call(f.receiver,'/members/'+f.receiver.id+'/role',{role:'member'},f.api2)])
  assert.deepEqual(results.map(r=>r.status).sort(),[200,409])
  assert.equal((await f.db.get("SELECT count(*) AS n FROM memberships WHERE org_id=$1 AND role='owner'",f.orgId))!.n,1)
  assert.equal((await f.db.get('SELECT status FROM invitations WHERE id=$1',pending.id))!.status,'cancelled')
})

test('Owner departure requires reauthentication and another active Owner; remaining accounts/devices survive',async t=>{
  const f=await lifecycle(t)
  assert.equal((await f.call(f.owner,'/members/'+f.owner.id+'/remove',{})).status,409)
  await f.recent();assert.equal((await f.call(f.owner,'/members/'+f.receiver.id+'/role',{role:'owner'})).status,200)
  assert.equal((await f.call(f.receiver,'/members/'+f.owner.id+'/remove',{})).status,403)
  await f.recent(f.receiver)
  const issued=await f.organizations.issueMember(f.owner.id,f.orgId,f.teamId,{id:'98',login:'future-member'})
  assert.equal((await f.call(f.receiver,'/members/'+f.owner.id+'/remove',{})).status,200)
  assert.equal(await f.db.get('SELECT 1 FROM memberships WHERE org_id=$1 AND user_id=$2',f.orgId,f.owner.id),undefined)
  assert.equal((await f.db.get('SELECT status FROM invitations WHERE id=$1',issued.id))!.status,'cancelled')
  assert.ok(await f.db.get('SELECT 1 FROM users WHERE id=$1',f.owner.id))
  assert.ok(await f.db.get('SELECT 1 FROM sessions WHERE token_hash=$1',f.owner.hash))
  await f.db.run("UPDATE memberships SET role='owner' WHERE org_id=$1 AND user_id=$2",f.orgId,f.other.id)
  await f.db.run('UPDATE users SET disabled=1 WHERE id=$1',f.other.id)
  assert.equal((await f.call(f.receiver,'/members/'+f.receiver.id+'/remove',{})).status,409)
})

test('organization deletion atomically closes requests/shares/uploads, removes scoped relationships and retains other organizations and global devices',async t=>{
  const f=await lifecycle(t), env=f.environment.id,org=f.orgId
  await f.organizations.setPermissions(f.owner.id,org,env,f.sender.id,true,true,true)
  const pending=await f.create(),committedRequest=randomUUID(),upload=randomUUID(),share=randomUUID(),attempt=randomUUID(),otherOrg=randomUUID(),otherTeam=randomUUID(),senderDevice=randomUUID()
  await f.db.run("INSERT INTO file_requests VALUES($1,$2,$3,$4,$5,$6,'fulfilled',$7,$8,NULL)",committedRequest,org,env,f.receiver.id,f.sender.id,f.identity.deviceId,f.now(),f.now()+DAY)
  await f.db.run("INSERT INTO devices VALUES($1,$2,'{}','active')",senderDevice,f.sender.id)
  await f.db.run("INSERT INTO uploads(id,request_id,org_id,sender_id,sender_device_id,project_id,size,digest,retention_days,status,created_at,available_until,sender_identity,receiver_identity) VALUES($1,$2,$3,$4,$5,$6,174,$7,1,'committed',$8,$9,'{}','{}')",upload,committedRequest,org,f.sender.id,senderDevice,f.project.id,'a'.repeat(43),f.now(),f.now()+DAY)
  await f.db.run("INSERT INTO external_shares(id,org_id,environment_id,creator_id,size,digest,retention_days,token_hash,status,created_at,available_until) VALUES($1,$2,$3,$4,40,$5,1,$5,'committed',$6,$7)",share,org,env,f.sender.id,'a'.repeat(43),f.now(),f.now()+DAY)
  await f.db.run("INSERT INTO external_shares(id,org_id,environment_id,creator_id,size,digest,retention_days,token_hash,status,created_at) VALUES($1,$2,$3,$4,40,$5,1,$5,'reserved',$6)",attempt,org,env,f.sender.id,'a'.repeat(43),f.now())
  await f.organizations.issueMember(f.owner.id,org,f.teamId,{id:'97',login:'future-member'})
  await f.db.run('INSERT INTO organizations(id,name) VALUES($1,$2)',otherOrg,'Keep')
  await f.db.run("INSERT INTO memberships VALUES($1,$2,'owner')",otherOrg,f.owner.id)
  await f.db.run('INSERT INTO teams VALUES($1,$2,$3,1)',otherTeam,otherOrg,'Keep')
  await f.db.run('INSERT INTO team_members VALUES($1,$2)',otherTeam,f.owner.id)
  assert.equal((await f.call(f.owner,'/remove',{})).status,403)
  await f.recent(f.sender);assert.equal((await f.call(f.sender,'/remove',{})).status,403)
  await f.recent()
  assert.equal((await f.db.get('SELECT ended_at FROM uploads WHERE id=$1',upload))!.ended_at,null)
  assert.equal((await f.db.get('SELECT ended_at FROM external_shares WHERE id=$1',share))!.ended_at,null)
  assert.equal((await f.call(f.owner,'/remove',{})).status,200)
  assert.equal((await f.db.get('SELECT active FROM organizations WHERE id=$1',org))!.active,0)
  assert.equal((await f.db.get('SELECT status FROM file_requests WHERE id=$1',pending.id))!.status,'cancelled')
  assert.equal((await f.db.get('SELECT revoked_at FROM uploads WHERE id=$1',upload))!.revoked_at,f.now())
  assert.equal((await f.db.get('SELECT token_hash FROM external_shares WHERE id=$1',share))!.token_hash,null)
  assert.equal((await f.db.get('SELECT status FROM external_shares WHERE id=$1',attempt))!.status,'cancelled')
  for(const table of ['memberships','teams','projects','invitations'])assert.equal((await f.db.get('SELECT count(*) AS n FROM '+table+' WHERE org_id=$1',org))!.n,0)
  assert.equal((await f.db.get('SELECT count(*) AS n FROM environments'))!.n,0)
  assert.equal((await f.db.get('SELECT count(*) AS n FROM environment_permissions'))!.n,0)
  assert.ok(await f.db.get('SELECT 1 FROM memberships WHERE org_id=$1 AND user_id=$2',otherOrg,f.owner.id))
  assert.ok(await f.db.get('SELECT 1 FROM team_members WHERE team_id=$1 AND user_id=$2',otherTeam,f.owner.id))
  assert.ok(await f.db.get('SELECT 1 FROM devices WHERE id=$1',f.identity.deviceId))
  assert.equal((await f.db.get('SELECT count(*) AS n FROM users'))!.n,4)
  assert.equal((await f.call(f.owner)).status,404)
  assert.equal((await f.db.get("SELECT count(*) AS n FROM organization_events WHERE org_id=$1 AND event='organization_deleted'",org))!.n,1)
  await f.api.prune()
  assert.equal((await f.db.get('SELECT deleted_at FROM external_shares WHERE id=$1',share))!.deleted_at,f.now())
  assert.equal((await f.db.get('SELECT deleted_at FROM uploads WHERE id=$1',upload))!.deleted_at,f.now())
})
